package com.djaeger.modemmonitor;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;

public class MainActivity extends Activity {
  final Handler h=new Handler(Looper.getMainLooper()); LinearLayout root; TextView hero,sub,updated; final Map<String,TextView> values=new LinkedHashMap<>(); boolean running=true;
  final String endpoint="http://192.168.1.1/djaeger-modem/status";
  int cyan=Color.rgb(66,211,255), bg=Color.rgb(7,16,24), card=Color.rgb(14,29,40), muted=Color.rgb(151,172,186);
  @Override public void onCreate(Bundle b){super.onCreate(b); build(); h.post(refresh);}
  @Override protected void onResume(){super.onResume();running=true;h.post(refresh);} @Override protected void onPause(){running=false;h.removeCallbacks(refresh);super.onPause();}
  TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setPadding(0,5,0,5);return v;}
  void build(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,40);root.setBackgroundColor(bg);sv.addView(root); TextView title=tv("DJAEGER // MODEM INTELLIGENCE",20,cyan);title.setTypeface(Typeface.DEFAULT_BOLD);root.addView(title);sub=tv("OpenWrt • 192.168.1.1 • Fast Recovery",12,muted);root.addView(sub);hero=tv("CONNECTING",34,Color.WHITE);hero.setTypeface(Typeface.DEFAULT_BOLD);root.addView(hero);updated=tv("Waiting for telemetry…",12,muted);root.addView(updated);String[] rows={"Health|score","Root Cause|root_domain","System Risk|system_risk","Modem|modem","Service / SIM|service_sim","WAN IP|wan_ip","RSRP|rsrp","RSRQ|rsrq","SINR|sinr","Gateway|gateway","Internet|internet","DNS|dns","AI Risk|adaptive_risk","AI Authority|ai_authority","AI Decision|ai_decision_action","Recovery|recovery","Last Action|last_action"};for(String r:rows){String[]p=r.split("\\|");addRow(p[0],p[1]);}Button x=new Button(this);x.setText("REFRESH NOW");x.setOnClickListener(v->{h.removeCallbacks(refresh);h.post(refresh);});root.addView(x);TextView note=tv("Read-only monitor. Recovery authority remains inside DJAEGER on OpenWrt.",11,muted);root.addView(note);setContentView(sv);}
  void addRow(String label,String key){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(20,12,20,12);box.setBackgroundColor(card);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,8,0,0);root.addView(box,bp);box.addView(tv(label.toUpperCase(),10,muted));TextView v=tv("—",17,Color.WHITE);v.setTypeface(Typeface.DEFAULT_BOLD);box.addView(v);values.put(key,v);}
  final Runnable refresh=new Runnable(){public void run(){if(!running)return;new Thread(()->load()).start();h.postDelayed(this,5000);}};
  void load(){try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(2500);c.setReadTimeout(2500);c.setUseCaches(false);int code=c.getResponseCode();if(code!=200)throw new IOException("HTTP "+code);BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream()));Map<String,String> m=new HashMap<>();String line;while((line=br.readLine())!=null){int i=line.indexOf('=');if(i>0)m.put(line.substring(0,i).trim(),line.substring(i+1).trim());}br.close();h.post(()->render(m));}catch(Exception e){h.post(()->offline(e.getMessage()));}}
  String g(Map<String,String>m,String k){String v=m.get(k);return v==null||v.length()==0?"—":v;} void put(String k,String v){TextView t=values.get(k);if(t!=null)t.setText(v);}
  void render(Map<String,String>m){String state=g(m,"state");hero.setText(state);hero.setTextColor(state.equals("HEALTHY")?Color.rgb(75,230,145):state.equals("RECOVERING")?Color.rgb(255,190,70):Color.rgb(255,100,100));updated.setText("LIVE • refresh 5s • epoch "+g(m,"updated"));put("score",g(m,"score")+" / 100");put("root_domain",g(m,"root_domain")+" • "+g(m,"root_confidence")+"%");put("system_risk",g(m,"system_risk")+" / 100 • "+g(m,"system_reason"));put("modem",g(m,"modem").equals("1")?"ONLINE":"OFFLINE");put("service_sim",g(m,"service")+" / "+g(m,"sim"));put("wan_ip",g(m,"wan_ip"));put("rsrp",g(m,"rsrp")+" dBm");put("rsrq",g(m,"rsrq")+" dB");put("sinr",g(m,"sinr")+" dB");put("gateway",g(m,"gateway").equals("1")?"OK":"FAIL");put("internet",g(m,"internet").equals("1")?"OK":"FAIL");put("dns",g(m,"dns").equals("1")?"OK":"FAIL");put("adaptive_risk",g(m,"adaptive_risk")+" / 100 • "+g(m,"adaptive_reason"));put("ai_authority",g(m,"ai_authority"));put("ai_decision_action",g(m,"ai_decision_action")+" • "+g(m,"ai_decision_confidence")+"%");put("recovery","stage "+g(m,"recovery_stage")+" • count "+g(m,"recovery_count"));put("last_action",g(m,"last_action"));}
  void offline(String why){hero.setText("MONITOR OFFLINE");hero.setTextColor(Color.rgb(255,100,100));updated.setText("Cannot reach OpenWrt telemetry • "+why);}
}
