plugins {
    id 'com.android.application'
}

android {
    namespace 'com.djaeger.batteryuisync'
    compileSdk 35

    defaultConfig {
        applicationId 'com.djaeger.batteryuisync'
        minSdk 27
        targetSdk 35
        versionCode 3
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
