plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hermes.workdashboard'
    compileSdk 35

    signingConfigs {
        release {
            storeFile file('hermes_work_terminal.jks')
            storePassword 'HermesWork2026'
            keyAlias 'hermeswork'
            keyPassword 'HermesWork2026'
        }
    }

    defaultConfig {
        applicationId "com.hermes.workdashboard"
        minSdk 23
        targetSdk 35
        versionCode 122
        versionName "1.2.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
