plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hermes.workinstaller'
    compileSdk 35

    signingConfigs {
        release {
            storeFile file('hermes_work_terminal.jks')
            storePassword 'HermesWork2026'
            keyAlias 'hermeswork'
            keyPassword 'HermesWork2026'
        }
    }

    defaultConfig {
        applicationId "com.hermes.workinstaller"
        minSdk 23
        targetSdk 35
        versionCode 100
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
