#!/usr/bin/env python3
from pathlib import Path
import re
root=Path('control-center-r2'); b=root/'app/build.gradle.kts'; m=root/'app/src/main/java/com/djaeger/controlcenter/MainActivity.kt'; r=root/'app/src/main/java/com/djaeger/controlcenter/DjaegerRepository.kt'; kv=root/'app/src/main/java/com/djaeger/controlcenter/KeyVault4.kt'
bs=b.read_text(); bs=re.sub(r'versionCode\s*=\s*\d+','versionCode = 12130',bs,count=1); bs=re.sub(r'versionName\s*=\s*"[^"]+"','versionName = "0.12.1-r13"',bs,count=1); b.write_text(bs)
rs=r.read_text()
if 'data class StrategyTruth(' not in rs:
 i=rs.index('data class RuntimeState('); rs=rs[:i]+'''data class StrategyTruth(val source:String="UNAVAILABLE",val proposal:String="UNAVAILABLE",val validation:String="UNAVAILABLE",val applied:String="UNAVAILABLE",val readback:String="UNAVAILABLE",val outcome:String="UNAVAILABLE",val cpuLittleMin:String="—",val cpuLittleMax:String="—",val cpuBigMin:String="—",val cpuBigMax:String="—",val gpuMin:String="—",val gpuMax:String="—",val cpuGovernor:String="—",val gpuGovernor:String="—",val powerBias:String="—",val burstLease:String="—",val comfortCeiling:String="—",val confidence:String="—",val rationale:String="Not published by current DJAEGER module",val fpsOutcome:String="—",val frameOutcome:String="—",val thermalOutcome:String="—",val powerOutcome:String="—",val learningSamples:String="—",val learningConfidence:String="—",val learningPromotion:String="—")\n\n'''+rs[i:]
mt=re.search(r'^data class RuntimeState\((.*)\)$',rs,re.MULTILINE); assert mt; decl=mt.group(0)
if 'val strategy:StrategyTruth' not in decl: rs=rs[:mt.start()]+decl[:-1]+',val strategy:StrategyTruth=StrategyTruth())'+rs[mt.end():]
needle='        RuntimeState(\n            root=true,'; assert needle in rs
truth='''        fun rv(vararg k:String):String{k.forEach{if(!rt[it].isNullOrBlank())return rt[it]!!};return "—"}\n        val strategy=StrategyTruth(source=rv("DECISION_SOURCE","decision_source","SOURCE"),proposal=rv("PIPELINE_PROPOSED","PROPOSED"),validation=rv("PIPELINE_VALIDATION","VALIDATION_STATUS"),applied=rv("PIPELINE_APPLIED","APPLIED_STATUS"),readback=rv("PIPELINE_READBACK","READBACK_STATUS"),outcome=rv("PIPELINE_OUTCOME","OUTCOME_STATUS"),cpuLittleMin=rv("CPU_LITTLE_MIN","STRATEGY_CPU_LITTLE_MIN"),cpuLittleMax=rv("CPU_LITTLE_MAX","STRATEGY_CPU_LITTLE_MAX"),cpuBigMin=rv("CPU_BIG_MIN","STRATEGY_CPU_BIG_MIN"),cpuBigMax=rv("CPU_BIG_MAX","STRATEGY_CPU_BIG_MAX"),gpuMin=rv("GPU_MIN","STRATEGY_GPU_MIN"),gpuMax=rv("GPU_MAX","STRATEGY_GPU_MAX"),cpuGovernor=rv("CPU_GOVERNOR","STRATEGY_CPU_GOVERNOR"),gpuGovernor=rv("GPU_GOVERNOR","STRATEGY_GPU_GOVERNOR"),powerBias=rv("POWER_BIAS","STRATEGY_POWER_BIAS"),burstLease=rv("BURST_LEASE","STRATEGY_BURST_LEASE"),comfortCeiling=rv("COMFORT_CEILING","STRATEGY_COMFORT_CEILING"),confidence=rv("STRATEGY_CONFIDENCE","CONFIDENCE"),rationale=rv("STRATEGY_RATIONALE","RATIONALE"),fpsOutcome=rv("OUTCOME_FPS","FPS_OUTCOME"),frameOutcome=rv("OUTCOME_FRAME_MS","FRAME_OUTCOME"),thermalOutcome=rv("OUTCOME_THERMAL","THERMAL_OUTCOME"),powerOutcome=rv("OUTCOME_POWER","POWER_OUTCOME"),learningSamples=rv("LEARNING_SAMPLES"),learningConfidence=rv("LEARNING_CONFIDENCE"),learningPromotion=rv("LEARNING_PROMOTION","LEARNING_STATUS"))\n\n'''; rs=rs.replace(needle,truth+needle,1)
needle2='            bugHealth=mapped.bugHealth\n'; assert needle2 in rs; rs=rs.replace(needle2,'            bugHealth=mapped.bugHealth,\n            strategy=strategy\n',1); r.write_text(rs)
# Android Keystore AES/GCM: no API key plaintext in SharedPreferences.
kv.write_text('''package com.djaeger.controlcenter\n\nimport android.content.Context\nimport android.security.keystore.KeyGenParameterSpec\nimport android.security.keystore.KeyProperties\nimport android.util.Base64\nimport java.security.KeyStore\nimport javax.crypto.Cipher\nimport javax.crypto.KeyGenerator\nimport javax.crypto.SecretKey\nimport javax.crypto.spec.GCMParameterSpec\n\nclass KeyVault4(private val context:Context){\n private val alias="djaeger_cc_vault4_aes"\n private val prefs=context.getSharedPreferences("djaeger_cc_vault4",Context.MODE_PRIVATE)\n private fun key():SecretKey{val ks=KeyStore.getInstance("AndroidKeyStore").apply{load(null)};val e=ks.getEntry(alias,null) as? KeyStore.SecretKeyEntry;if(e!=null)return e.secretKey;val kg=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");kg.init(KeyGenParameterSpec.Builder(alias,KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());return kg.generateKey()}\n fun put(slot:Int,value:String){require(slot in 1..4);require(value.isNotBlank());val c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key());prefs.edit().putString("s$slot",Base64.encodeToString(c.iv,Base64.NO_WRAP)+":"+Base64.encodeToString(c.doFinal(value.toByteArray()),Base64.NO_WRAP)).apply()}\n fun get(slot:Int):String?{require(slot in 1..4);val raw=prefs.getString("s$slot",null)?:return null;return runCatching{val p=raw.split(":",limit=2);val c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),GCMParameterSpec(128,Base64.decode(p[0],Base64.NO_WRAP)));String(c.doFinal(Base64.decode(p[1],Base64.NO_WRAP)))}.getOrNull()}\n fun delete(slot:Int){require(slot in 1..4);prefs.edit().remove("s$slot").apply()}\n fun status():String=(1..4).joinToString(" • "){"KEY $it: "+if(prefs.contains("s$it"))"•••• SAVED" else "EMPTY"}\n}\n''')
ms=m.read_text().replace('CONTROL CENTER • v0.12.1-r12 • USER DESIGN • REALTIME 1s','CONTROL CENTER • v0.12.1-r13 • COMPLETE USER DESIGN • REALTIME 1s')
start=ms.index('@Composable fun StrategyCompositionCard(s:RuntimeState)'); end=ms.index('@Composable fun ThermalRow(s:RuntimeState)',start)
cards='''@Composable fun StrategyCompositionCard(s:RuntimeState){val x=s.strategy;BoxCard("STRATEGY COMPOSITION","Source: ${x.source}\\nMode: ${s.userMode}\\nCPU LITTLE: ${x.cpuLittleMin} → ${x.cpuLittleMax}\\nCPU BIG: ${x.cpuBigMin} → ${x.cpuBigMax}\\nGPU: ${x.gpuMin} → ${x.gpuMax}\\nCPU governor: ${x.cpuGovernor} • GPU governor: ${x.gpuGovernor}\\nPower/bias: ${x.powerBias} • Burst/lease: ${x.burstLease}\\nComfort ceiling: ${x.comfortCeiling} • Confidence: ${x.confidence}\\nRationale: ${x.rationale}",true)}\n@Composable fun DecisionPipelineCard(s:RuntimeState){val x=s.strategy;BoxCard("DECISION PIPELINE","PROPOSED: ${x.proposal}\\nVALIDATED / REJECTED: ${x.validation}\\nAPPLIED: ${x.applied}\\nREADBACK VERIFIED: ${x.readback}\\nOUTCOME: ${x.outcome}\\nDecision source: ${x.source}",true)}\n@Composable fun OutcomeLearningCard(s:RuntimeState){val x=s.strategy;BoxCard("OUTCOME + LEARNING","FPS: ${x.fpsOutcome} • Frame: ${x.frameOutcome}\\nThermal: ${x.thermalOutcome} • Power: ${x.powerOutcome}\\nLearning samples: ${x.learningSamples}\\nLearning confidence: ${x.learningConfidence}\\nPromotion: ${x.learningPromotion}\\nOnly module-published truth is displayed; missing fields remain unavailable.",true)}\n\n'''; ms=ms[:start]+cards+ms[end:]
anchor='OutlinedTextField(value=keyInput'; assert anchor in ms
prefix='''val vaultContext=androidx.compose.ui.platform.LocalContext.current\n        val vault4=remember(vaultContext){KeyVault4(vaultContext)}\n        var vaultSlot by remember{mutableStateOf(1)}\n        var vaultEpoch by remember{mutableStateOf(0)}\n        val vaultStatus4=remember(vaultEpoch){vault4.status()}\n        BoxCard("GEMINI KEY VAULT • 4 MANUAL SLOTS",vaultStatus4+"\\nActive: KEY $vaultSlot\\nManual selection only. HTTP 429 never rotates keys automatically.",true)\n        Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){(1..4).forEach{n->OutlinedButton(onClick={vaultSlot=n},modifier=Modifier.weight(1f)){Text("KEY $n")}}}\n        Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick={if(keyInput.isNotBlank()){{vault4.put(vaultSlot,keyInput);keyInput="";vaultEpoch++}}},enabled=keyInput.isNotBlank(),modifier=Modifier.weight(1f)){Text("SAVE SLOT")};Button(onClick={{val k=vault4.get(vaultSlot);if(k!=null){{keyInput=k;bridgeOp="SAVE_KEY"}}}},modifier=Modifier.weight(1f)){Text("SELECT")};Button(onClick={{vault4.delete(vaultSlot);vaultEpoch++}},modifier=Modifier.weight(1f)){Text("DELETE SLOT")}}\n        '''
# Fix doubled braces introduced to keep Python f-string irrelevant; Kotlin needs single braces.
prefix=prefix.replace('{{','{').replace('}}','}')
ms=ms.replace(anchor,prefix+anchor,1); m.write_text(ms)
print('R13_BASELINE=R11_ADDITIVE');print('R13_STRATEGY_TRUTH=MODULE_PUBLISHED_ONLY');print('R13_PIPELINE=BOUND');print('R13_OUTCOME_LEARNING=BOUND');print('R13_KEY_VAULT=FOUR_MANUAL_SLOTS_AES_GCM');print('R13_429_AUTOROTATE=DISABLED_BY_DESIGN')
