#!/usr/bin/env python3
from pathlib import Path
import re
root=Path('control-center-r2'); b=root/'app/build.gradle.kts'; m=root/'app/src/main/java/com/djaeger/controlcenter/MainActivity.kt'; r=root/'app/src/main/java/com/djaeger/controlcenter/DjaegerRepository.kt'
bs=b.read_text(); bs=re.sub(r'versionCode\s*=\s*\d+','versionCode = 12130',bs,count=1); bs=re.sub(r'versionName\s*=\s*"[^"]+"','versionName = "0.12.1-r13"',bs,count=1); b.write_text(bs)
rs=r.read_text()
if 'data class StrategyTruth(' not in rs:
 i=rs.index('data class RuntimeState('); rs=rs[:i]+'''data class StrategyTruth(val source:String="UNAVAILABLE",val proposal:String="UNAVAILABLE",val validation:String="UNAVAILABLE",val applied:String="UNAVAILABLE",val readback:String="UNAVAILABLE",val outcome:String="UNAVAILABLE",val cpuLittleMin:String="—",val cpuLittleMax:String="—",val cpuBigMin:String="—",val cpuBigMax:String="—",val gpuMin:String="—",val gpuMax:String="—",val cpuGovernor:String="—",val gpuGovernor:String="—",val powerBias:String="—",val burstLease:String="—",val comfortCeiling:String="—",val confidence:String="—",val rationale:String="Not published by current DJAEGER module",val fpsOutcome:String="—",val frameOutcome:String="—",val thermalOutcome:String="—",val powerOutcome:String="—",val learningSamples:String="—",val learningConfidence:String="—",val learningPromotion:String="—")\n\n'''+rs[i:]
mt=re.search(r'^data class RuntimeState\((.*)\)$',rs,re.MULTILINE); assert mt; decl=mt.group(0)
if 'val strategy:StrategyTruth' not in decl: rs=rs[:mt.start()]+decl[:-1]+',val strategy:StrategyTruth=StrategyTruth())'+rs[mt.end():]
needle='        RuntimeState(\n            root=true,'; assert needle in rs
truth='''        fun rv(vararg k:String):String{k.forEach{if(!rt[it].isNullOrBlank())return rt[it]!!};return "—"}\n        val strategy=StrategyTruth(source=rv("DECISION_SOURCE","decision_source","SOURCE"),proposal=rv("PIPELINE_PROPOSED","PROPOSED"),validation=rv("PIPELINE_VALIDATION","VALIDATION_STATUS"),applied=rv("PIPELINE_APPLIED","APPLIED_STATUS"),readback=rv("PIPELINE_READBACK","READBACK_STATUS"),outcome=rv("PIPELINE_OUTCOME","OUTCOME_STATUS"),cpuLittleMin=rv("CPU_LITTLE_MIN","STRATEGY_CPU_LITTLE_MIN"),cpuLittleMax=rv("CPU_LITTLE_MAX","STRATEGY_CPU_LITTLE_MAX"),cpuBigMin=rv("CPU_BIG_MIN","STRATEGY_CPU_BIG_MIN"),cpuBigMax=rv("CPU_BIG_MAX","STRATEGY_CPU_BIG_MAX"),gpuMin=rv("GPU_MIN","STRATEGY_GPU_MIN"),gpuMax=rv("GPU_MAX","STRATEGY_GPU_MAX"),cpuGovernor=rv("CPU_GOVERNOR","STRATEGY_CPU_GOVERNOR"),gpuGovernor=rv("GPU_GOVERNOR","STRATEGY_GPU_GOVERNOR"),powerBias=rv("POWER_BIAS","STRATEGY_POWER_BIAS"),burstLease=rv("BURST_LEASE","STRATEGY_BURST_LEASE"),comfortCeiling=rv("COMFORT_CEILING","STRATEGY_COMFORT_CEILING"),confidence=rv("STRATEGY_CONFIDENCE","CONFIDENCE"),rationale=rv("STRATEGY_RATIONALE","RATIONALE"),fpsOutcome=rv("OUTCOME_FPS","FPS_OUTCOME"),frameOutcome=rv("OUTCOME_FRAME_MS","FRAME_OUTCOME"),thermalOutcome=rv("OUTCOME_THERMAL","THERMAL_OUTCOME"),powerOutcome=rv("OUTCOME_POWER","POWER_OUTCOME"),learningSamples=rv("LEARNING_SAMPLES"),learningConfidence=rv("LEARNING_CONFIDENCE"),learningPromotion=rv("LEARNING_PROMOTION","LEARNING_STATUS"))\n\n'''; rs=rs.replace(needle,truth+needle,1)
needle2='            bugHealth=mapped.bugHealth\n'; assert needle2 in rs; rs=rs.replace(needle2,'            bugHealth=mapped.bugHealth,\n            strategy=strategy\n',1); r.write_text(rs)
ms=m.read_text().replace('CONTROL CENTER • v0.12.1-r12 • USER DESIGN • REALTIME 1s','CONTROL CENTER • v0.12.1-r13 • COMPLETE USER DESIGN • REALTIME 1s')
start=ms.index('@Composable fun StrategyCompositionCard(s:RuntimeState)'); end=ms.index('@Composable fun ThermalRow(s:RuntimeState)',start)
cards='''@Composable fun StrategyCompositionCard(s:RuntimeState){val x=s.strategy;BoxCard("STRATEGY COMPOSITION","Source: ${x.source}\\nMode: ${s.userMode}\\nCPU LITTLE: ${x.cpuLittleMin} → ${x.cpuLittleMax}\\nCPU BIG: ${x.cpuBigMin} → ${x.cpuBigMax}\\nGPU: ${x.gpuMin} → ${x.gpuMax}\\nCPU governor: ${x.cpuGovernor} • GPU governor: ${x.gpuGovernor}\\nPower/bias: ${x.powerBias} • Burst/lease: ${x.burstLease}\\nComfort ceiling: ${x.comfortCeiling} • Confidence: ${x.confidence}\\nRationale: ${x.rationale}",true)}\n@Composable fun DecisionPipelineCard(s:RuntimeState){val x=s.strategy;BoxCard("DECISION PIPELINE","PROPOSED: ${x.proposal}\\nVALIDATED / REJECTED: ${x.validation}\\nAPPLIED: ${x.applied}\\nREADBACK VERIFIED: ${x.readback}\\nOUTCOME: ${x.outcome}\\nDecision source: ${x.source}",true)}\n@Composable fun OutcomeLearningCard(s:RuntimeState){val x=s.strategy;BoxCard("OUTCOME + LEARNING","FPS: ${x.fpsOutcome} • Frame: ${x.frameOutcome}\\nThermal: ${x.thermalOutcome} • Power: ${x.powerOutcome}\\nLearning samples: ${x.learningSamples}\\nLearning confidence: ${x.learningConfidence}\\nPromotion: ${x.learningPromotion}\\nOnly module-published truth is displayed; missing fields remain unavailable.",true)}\n\n'''; ms=ms[:start]+cards+ms[end:]
# Inject explicit 4-slot selector immediately before the existing stable vault-index input.
anchor='OutlinedTextField(value=vaultIndex,onValueChange={vaultIndex=it.filter(Char::isDigit)},label={Text("Vault index")}'
assert anchor in ms,'vault-index-anchor-not-found'
prefix='''BoxCard("GEMINI KEY VAULT • 4 MANUAL SLOTS",vaultStatus+"\\nSlots: KEY 1 • KEY 2 • KEY 3 • KEY 4\\nSelection is manual. HTTP 429 never rotates keys automatically.",true)\n        Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("1","2","3","4").forEach{n->OutlinedButton(onClick={vaultIndex=n},modifier=Modifier.weight(1f)){Text("KEY $n")}}}\n        '''
ms=ms.replace(anchor,prefix+anchor,1)
ms=ms.replace('onValueChange={vaultIndex=it.filter(Char::isDigit)}','onValueChange={vaultIndex=it.filter(Char::isDigit).take(1)}',1).replace('label={Text("Vault index")}', 'label={Text("Active slot 1–4")}',1)
ms=ms.replace('enabled=bridgeOp==null&&vaultIndex.isNotBlank()', 'enabled=bridgeOp==null&&vaultIndex in listOf("1","2","3","4")')
m.write_text(ms)
print('R13_BASELINE=R11_ADDITIVE'); print('R13_STRATEGY_TRUTH=MODULE_PUBLISHED_ONLY'); print('R13_PIPELINE=BOUND'); print('R13_OUTCOME_LEARNING=BOUND'); print('R13_KEY_VAULT=FOUR_MANUAL_SLOTS'); print('R13_429_AUTOROTATE=DISABLED_BY_DESIGN')
