plugins { id 'com.android.application' }

android {
    namespace 'com.djaeger.norebootrecovery'
    compileSdk 35
    defaultConfig {
        applicationId 'com.djaeger.norebootrecovery'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName '1.0-recovery1'
    }
    buildTypes { release { minifyEnabled false; shrinkResources false } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
